### PR TITLE
Refactor: Clean current artifact.json values

### PR DESCRIPTION
**Pull request by 0xGabi**
To ensure we have one single artifact.json across different networks. We have to remove `appId` and `appName` for the network as root values. They were useful on the aragonCLI internal context. Instead, we can access those from:

```
environment: {
	network1: {
		appId: 'somevalue',
		appName: 'otherValue'
	}
}
```

### CODE REVIEW

**Comment by dapplion** [comment]
Is the client expecting a specific network or it would take whatever?

**Comment by 0xGabi** [comment]
Let's double-check with @sohkai about how the Client uses the artifact.json file

**Comment by dapplion** [comment]
> Let's double-check with @sohkai about how the Client uses the artifact.json file

LGTM! Let's see if Brett says ok

**Comment by 0xGabi** [comment]
Brett's answer:

This is where aragon.js fetches the artifact: https://github.com/aragon/aragon.js/blob/master/packages/aragon-wrapper/src/core/apm/repo.js#L55

The client then uses the resulting object, merged with other app details

**Comment by dapplion** [comment]
> Brett's answer:
> 
> > This is where aragon.js fetches the artifact: https://github.com/aragon/aragon.js/blob/master/packages/aragon-wrapper/src/core/apm/repo.js#L55
> > The client then uses the resulting object, merged with other app details (manifest.json)

Brett confirms that in the wrapper / client the props
```
artifact.appName
artifact.appId
```
are used while the props
```
artifact.enviornment
artifact.env
```
are not used

**Comment by 0xGabi** [comment]
Yes, I agree with the above. Deprecate the environment object makes sense giving we handle all that and buidler config is much more flexible.

**Comment by 0xGabi** [comment]
After discussing, we will not modify the `artifact.json` until we are sure about the compatibility implications.

**Pull request closed without merging**
