### PR TITLE
Small style name update

### PR DESCRIPTION
**Pull request by 0xGabi**

### CODE REVIEW

**Comment by dapplion** [comment]
It's very important for the AST parsers that this is not just the source code but the flat code of all the contract dependencies. Otherwise bad things can happen. The name should leave very clear the flat code is needed

**Comment by 0xGabi** [comment]
Yes, that's a good point. Let's leave it like it is 👍

**Comment by sohkai** [comment]
Just a note on this—the reason I mentioned `sourceCode` is that the next function had an argument like `functionsOrSourceCode` and we should change that one instead.

**Comment by dapplion** [comment]
> Just a note on this—the reason I mentioned `sourceCode` is that the next function had an argument like `functionsOrSourceCode` and we should change that one instead.

Oh you are right! Added a todo with it to this issue https://github.com/aragon/buidler-aragon/pull/122#issuecomment-608571254

**Pull request closed without merging**
